# .github/workflows/release.yml

name: Build and Release for Windows

# This workflow runs when you push a tag that starts with 'v' (e.g., v1.1.8)
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # A single job to build the app and create the release
  build-and-release:
    name: Build and Release Windows
    # This job will run only on a Windows virtual machine
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: './Rhythm Dock'

      - name: Build Windows Application (x64 & ia32)
        # This command builds both the 32-bit and 64-bit installers
        run: npm run dist -- --win --x64 --ia32
        working-directory: './Rhythm Dock'

      - name: Create and Publish Release
        # This single step creates the release and uploads the .exe files
        uses: ncipollo/release-action@v1
        with:
          # The 'artifact' property finds and uploads all matching files
          artifact: './Rhythm Dock/dist/*.exe'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false # Set to false if you want to publish automatically